#
# docker compose -f docker-compose.yml up

version: '3.8'

name: db_indexes

services:
  # port: 5432
  psql:
    # restart: always
    image: postgres:15.1-bullseye
    user: root
    environment:
      POSTGRES_PASSWORD: qwerty
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./PGSQL:/var/lib/postgresql/data/pgdata

  rails:
    tty: true
    stdin_open: true
    image: iamteacher/rails7:latest
    working_dir: /app
    volumes:
      - ./app:/app
    depends_on:
      - psql
