defaults: &defaults
  pool: 10
  host: psql
  username: postgres
  database: db_indexes
  password: qwerty

test:
  adapter:  postgresql
  encoding: unicode
  <<: *defaults

development:
  adapter:  postgresql
  encoding: unicode
  <<: *defaults
